CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORY (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
